# Ez theme 
# Created by VadimP22 (https://github.com/vadimp22)
# Feel free to steal/port/rename :)

# Syntax
"comment" = { fg = "dark_base4" }
"attribute" = { fg = "magenta" }

"keyword" = { fg = "orange", modifiers = ["bold"] }
"keyword.control" = { fg = "orange", modifiers = ["bold"] }
"keyword.directive" = { fg = "dark_orange" }
"keyword.storage.modifier" = { fg = "lime", modifiers = ["bold"] }
"keyword.function" = { fg = "lime", modifiers = ["bold"] }

"type" = { fg = "blue" }
"type.builtin" = { fg = "blue", modifiers = ["bold"] }

"constant" = { fg = "magenta" }
"constant.builtin" = { fg = "magenta", modifiers = ["bold"] }
"string" = { fg = "green" }

"variable" = { fg = "base5" }
"variable.parameter" = { fg = "dark_aqua" }

"punctuation" = { fg = "base4" }
"punctuation.bracket" = { fg = "base5" }
"operator" = { fg = "dark_blue" }

"function" = { fg = "red" }
"function.builtin" = { fg = "red", modifiers = ["bold"]}
"function.macro" = { fg = "aqua" }

"namespace" = { fg = "dark_blue" }

# Markup
"markup.heading" = { fg = "red", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "dark_red", modifiers = ["bold"] }
"markup.list" = { fg = "lime", modifiers = ["bold"] }
"markup.bold" = { fg = "magenta", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base4" }
"markup.link.text" = { fg = "blue" }
"markup.link.label" = { fg = "blue" }
"markup.quote" = { fg = "yellow" }
"markup.raw" = { fg = "aqua" }

# Errors
"warning" = "yellow"
"error" = "red"
"info" = "aqua"
"hint" = "base5"

"diagnostic.warning" = { underline = { color = "yellow", style = "curl"} }
"diagnostic.error" = { underline = { color = "red", style = "curl"} }
"diagnostic.info" = { underline = { color = "aqua", style = "curl"} }
"diagnostic.hint" = { underline = { color = "base5", style = "curl"} }

# UI common
"ui.background" = { bg = "dark_base0" }
"ui.text" = { fg = "dark_base5" }
"ui.text.focus" = { fg = "base6", bg = "base2", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "base3" }
"ui.text.info" = { fg = "base5" }
"ui.linenr" = { fg = "dark_base3" }
"ui.linenr.selected" = { fg = "base4", modifiers = ["bold"] }
"ui.cursorline" = { bg = "base1" }
"ui.selection" = { bg = "base2" }
"ui.cursor" = { bg = "base5", fg = "dark_base0" }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold", "underlined"] }

# UI menus
"ui.menu" = { bg = "base1", fg = "base5" }
"ui.menu.selected" = { bg = "base5", fg = "base1" }
"ui.popup" = { fg = "base4", bg = "base0" }
"ui.help" = { fg = "base6", bg = "base2" }
"ui.highlight" = { bg = "base2" }
"special" = "lime"

# UI editor
"ui.virtual.indent-guide" = { fg = "base2" }
"ui.virtual.ruler" = { bg = "base0" }
"ui.gutter" = { fg = "base1" }
"ui.gutter.selected" = { fg = "base3" }
"ui.window" = { fg = "base1" }

# Statusline
"ui.statusline" = { bg = "dark_base3", fg = "base5" }
"ui.statusline.inactive" = { bg = "base1", fg = "base4" }
"ui.statusline.normal" = { bg = "base5", fg = "dark_base0", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "lime", fg = "dark_base0", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "magenta", fg = "dark_base0", modifiers = ["bold"] }

# Bufferline
"ui.bufferline" = { bg = "dark_base1", fg = "base4" }
"ui.bufferline.active" = { bg = "base3", fg = "base5", modifiers = ["bold"] }

# Diff
"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"


[palette]
yellow = "#FFBF60"
orange = "#FF6F50"
red = "#E53353"
magenta = "#A967D2"
blue = "#556DED"
aqua = "#45BDB6"
green = "#58B058"
lime = "#CCFF5F"

dark_yellow = "#A57C3E"
dark_orange = "#A95543"
dark_red = "#852234"
dark_magenta = "#6F4588"
dark_blue = "#354287"
dark_aqua = "#226B67"
dark_green = "#467A46"
dark_lime = "#82955A"

base0 = "#111216"
base1 = "#14161B"
base2 = "#20222B"
base3 = "#2E343F"
base4 = "#3F4756"
base5 = "#8D9ABA"
base6 = "#C3D2F9"

dark_base0 = "#0D0E11"
dark_base1 = "#121418"
dark_base2 = "#191B22"
dark_base3 = "#282D37"
dark_base4 = "#39404E"
dark_base5 = "#76819E"
dark_base6 = "#A7B5DA"
