# Ez theme 
# Created by VadimP22 (https://github.com/vadimp22)
# Feel free to steal/port/rename :)

# Syntax
"comment" = { fg = "base3" }
"attribute" = { fg = "magenta" }

"keyword" = { fg = "orange", modifiers = ["bold"] }
"keyword.control" = { fg = "orange", modifiers = ["bold"] }
"keyword.directive" = { fg = "red" }
"keyword.storage.modifier" = { fg = "dark_orange", modifiers = ["bold"] }
"keyword.function" = { fg = "lime", modifiers = ["bold"] }

"type" = { fg = "blue" }
"type.builtin" = { fg = "blue", modifiers = ["bold"] }

"constant" = { fg = "magenta" }
"constant.builtin" = { fg = "magenta", modifiers = ["bold"] }
"string" = { fg = "green" }

"variable" = { fg = "base5" }
"variable.parameter" = { fg = "dark_aqua" }

"punctuation" = { fg = "base4" }
"operator" = { fg = "dark_blue" }

"function" = { fg = "aqua" }
"function.builtin" = { fg = "aqua", modifiers = ["bold"]}
"function.macro" = { fg = "red" }

"namespace" = { fg = "dark_blue" }

# Errors
"warning" = "yellow"
"error" = "red"
"info" = "aqua"
"hint" = "base5"

"diagnostic.warning" = { underline = { color = "yellow", style = "curl"} }
"diagnostic.error" = { underline = { color = "red", style = "curl"} }
"diagnostic.info" = { underline = { color = "aqua", style = "curl"} }
"diagnostic.hint" = { underline = { color = "base5", style = "curl"} }

# UI common
"ui.background" = { bg = "base0" }
"ui.text" = { fg = "base5" }
"ui.text.focus" = { fg = "lime", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "base3" }
"ui.text.info" = { fg = "base5" }
"ui.linenr" = { fg = "base2" }
"ui.linenr.selected" = { fg = "base3", modifiers = ["bold"] }
"ui.cursorline" = { bg = "base1" }
"ui.selection" = { bg = "base2" }
"ui.cursor" = { bg = "base5", fg = "base0" }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold", "underlined"] }

# UI menus
"ui.menu" = { bg = "base1", fg = "base5" }
"ui.menu.selected" = { bg = "base5", fg = "base1" }
"ui.popup" = { fg = "base4", bg = "base1" }
"ui.highlight" = "blue"
"special" = "dark_blue"

# UI editor
"ui.virtual.indent-guide" = { fg = "base2" }
"ui.virtual.ruler" = { bg = "base1" }
"ui.gutter" = { fg = "base1" }
"ui.gutter.selected" = { fg = "base3" }
"ui.window" = { fg = "base1" }

# Statusline
"ui.statusline" = { bg = "base2", fg = "base5" }
"ui.statusline.inactive" = { bg = "base1", fg = "base4" }
"ui.statusline.normal" = { bg = "base5", fg = "base0", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "lime", fg = "base0", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "magenta", fg = "base0", modifiers = ["bold"] }

# Diff
"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"


[palette]
yellow = "#FFBF60"
orange = "#FF6F50"
red = "#E53353"
magenta = "#A967D2"
blue = "#556DED"
aqua = "#45BDB6"
green = "#58B058"
lime = "#CCFF5F"

dark_yellow = "#A57C3E"
dark_orange = "#A95543"
dark_red = "#852234"
dark_magenta = "#6F4588"
dark_blue = "#384CB5"
dark_aqua = "#226B67"
dark_green = "#467A46"
dark_lime = "#82955A"

base0 = "#0D0E11"
base1 = "#14161B"
base2 = "#20222B"
base3 = "#2E343F"
base4 = "#3F4756"
base5 = "#8D9ABA"
