# Based on Flexoki: https://stephango.com/flexoki and Papercolor
# Modified by Vadim Petrov (VadimP22)

"ui.background" = { bg = "bg" }
"ui.cursor" = { fg = "tx", bg = "tx-3" }
"ui.cursor.primary" = { fg = "bg", bg = "tx" }
"ui.cursor.match" = { modifiers = ["bold"] }
"ui.linenr" = "tx-3"
"ui.linenr.selected" = "tx"
"ui.selection" = { bg = "ui-2" }
"ui.statusline" = { fg = "tx", bg = "bg-2" }
"ui.statusline.normal" = { fg = "bg", bg = "bl" }
"ui.statusline.insert" = { fg = "bg", bg = "or" }
"ui.statusline.select" = { fg = "bg", bg = "ma" }
"ui.cursorline" = { bg = "bg-2" }
"ui.popup" = { fg = "tx", bg = "bg-2" }
"ui.window" = "tx"
"ui.help" = { fg = "tx", bg = "bg" }
"ui.text" = "tx"
"ui.text.focus" = { bg = "bg-2", fg = "tx" }
"ui.text.info" = "tx"
"ui.virtual.whitespace" = "bg-2"
"ui.virtual.ruler" = { bg = "bg-2" }
"ui.virtual.inlay-hint" = { fg = "tx-3", bg = "bg" }
"ui.virtual.jump-label" = { bg = "bg-2", modifiers = ["bold"]}
"ui.menu" = { fg = "tx", bg = "bg" }
"ui.menu.selected" = { bg = "ui", fg = "tx" }
"ui.debug" = { fg = "or", bg = "bg" }
"ui.highlight.frameline" = { bg = "yellow" }
"diagnostic.hint" = { underline = { color = "bl", style = "curl" } }
"diagnostic.info" = { underline = { color = "bl", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "re", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
"hint" = { fg = "bl", modifiers = ["bold"] }
"info" = { fg = "yellow", modifiers = ["bold"] }
"warning" = { fg = "or", modifiers = ["bold"] }
"error" = { fg = "re", modifiers = ["bold"] }

"attribute" = "yellow"
"type" = "ma"
"constructor" = "gr"
"constant" = "pu"
"constant.builtin" = "cyan"
"string" = "cy"
"string.regexp" = "or"
"string.special" = "yellow"
"comment" = "tx-3"
"variable" = "tx"
"variable.builtin" = "ma"
"variable.other" = "bl"
"punctuation" = "tx-2"
"keyword" = "gr"
"keyword.control" = "pink"
"keyword.control.conditional" = "gr"
"keyword.control.import" = "yellow"
"keyword.control.return" = "gr"
"keyword.function" = "gr"
"keyword.storage.type" = "bl"
"keyword.storage.modifier" = "bl"
"operator" = "tx-2"
"function" = "or"
"tag" = "bl"
"namespace" = "re"

"markup.heading" = "or"
"markup.list" = "yellow"
"markup.bold" = { fg = "or", modifiers = ["bold"] }
"markup.italic" = { fg = "or", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.raw.block" = "or"
"markup.link.url" = "bl"
"markup.link.text" = "yellow"
"markup.link.label" = "gr"
"markup.quote" = "yellow"
"markup.raw" = "bl"
"diff.plus" = "gr"
"diff.minus" = "re"
"diff.delta" = "yellow"

"special" = "bl"
"ui.bufferline" = { bg = "bg", fg = "tx-3"}
"ui.bufferline.active" = { bg = "bg-2", fg = "tx" }

[palette]
# From flexoki dark
tx = "#CECDC3"
tx-2 = "#878580"
tx-3 = "#575653"
ui-3 = "#403E3C"
ui-2 = "#343331"
ui = "#282726"
bg-2 = "#1C1B1A"
bg = "#100F0F"

re = "#D14D41"
or = "#DA702C"
ye = "#D0A215"
gr = "#879A39"
cy = "#3AA99F"
bl = "#4385BE"
pu = "#8B7EC8"
ma = "#CE5D97"

# From papercolor dark
black = "#1c1c1c"
red = "#af005f"
green = "#5faf00"
green-2 = "#5faf5f"
yellow = "#d7af5f"
blue = "#5fafd7"
gray = "#808080"
orange = "#d7875f"
white = "#d0d0d0"
magenta = "#af87d7"
pink = "#ff5faf"
cyan = "#00afaf"

light-black = "#585858"
light-green = "#afd700"
light-orange = "#ffaf00"
light-white = "#5f8787"
