# Author: André Sá <enkodr@outlook.com>
# Based on the AYU theme colors from https://github.com/dempfi/ayu

# Syntax highlighting
"type" = { fg = "#9ce878" }
"type.builtin" = { fg = "#249388" }
"constructor" = { fg = "#9ce878" }
"constant" = { fg = "#e4f279" }
"string" = { fg = "#c5d671" }
"string.regexp" = { fg = "#c5d671" }
"string.special" = { fg = "#c5d671" }
"comment" = { fg = "#2c3f51", modifiers = ["italic"] }
"variable" = "foreground"
"label" = { fg = "#c5d671" }
"punctuation" = "foreground"
"keyword" = { fg = "#246c82" }
"keyword.control" = { fg = "#476683" }
"keyword.directive" = { fg = "#476683" }
"operator" = "foreground"
"function" = { fg = "#1a9d6b" }
"tag" = { fg = "#249388" }
"namespace" = { fg = "#249388" }
"markup.heading" = "foreground"
"markup.list" = "foreground"
"markup.raw.block" = "foreground"
"markup.link.url" = "foreground"
"markup.link.text" = "foreground"
"markup.link.label" = "foreground"
"markup.quote" = "foreground"
"diff.plus" =  "yellow"
"diff.minus" = "red"
"diff.delta" = "green"

# "diff.plus" =  "#A6E22E"
# "diff.minus" = "#e61f44"
# "diff.delta" = "#f7b83d"

# Interface
"ui.background"= { bg = "background" }
# "ui.background" = {}
"ui.cursor" = { fg = "background", bg = "foreground" }
"ui.cursor.match" = { fg = "yellow", underline = { color = "yellow", style = "line"} }
"ui.linenr" = { fg = "#1b2632" }
"ui.linenr.selected" = "foreground"
#"ui.statusline" = { fg = "background", bg = "#9cadbc" }
"ui.statusline" = { fg = "background", bg = "#1b2632" }
"ui.statusline.select" = { fg = "background", bg = "orange"}
"ui.statusline.normal" = { fg = "background", bg = "foreground"}
"ui.statusline.insert" = { fg = "background", bg = "yellow"}
"ui.cursorline" = {}
"ui.popup" = { fg = "foreground", bg = "black" }
"ui.window" = "dark_gray"
"ui.help" = { fg = "#7B91b3", bg = "black" }
"ui.text" = "foreground"
"ui.text.focus" = { bg = "dark_gray", fg = "foreground" }
"ui.text.info" = "foreground"
"ui.virtual.whitespace" = "dark_gray"
"ui.virtual.ruler" = { bg = "black" }
"ui.menu" = { fg = "foreground", bg = "black" }
"ui.menu.selected" = { bg = "gray", fg = "background" }
"ui.selection" = { bg = "dark_gray" }
"warning" = "yellow"
"error" = { fg = "red", modifiers = ["bold"] }
"info" = { fg = "foreground", modifiers = ["bold"] }
"hint" = { fg = "blue", modifiers = ["bold"] }
"diagnostic.hint"= { underline = { color = "blue", style = "curl" } }
"diagnostic.info"= { underline = { color = "blue", style = "curl" } }
"diagnostic.warning"= { underline = { color = "yellow", style = "curl" } }
"diagnostic.error"= { underline = { color = "red", style = "curl" } }
"ui.bufferline" = { fg = "gray", bg = "background" }
"ui.bufferline.active" = { fg = "foreground", bg = "dark_gray" }

#"special" = "#9ce878"
"special" = "orange"

[palette]
background = "#090d11"
foreground = "#9cadbc"

black = "#121a22"
blue = "#1a9d6b"
dark_gray = "#323843"
cyan = "#1a9d6b"
gray = "#565b66"
green = "#249388"
magenta = "#246c82"
orange = "#ffad66"
red = "#ba0e2e"
yellow = "#9ce878"

