# Nostalgia theme 
# Inspired by MS Visual Studio colors
# Created by VadimP22 (https://github.com/vadimp22)
# Feel free to steal/port/rename :)

# Syntax
"comment" = { fg = "comment" }
"attribute" = { fg = "black" }

"keyword" = { fg = "error" }
"keyword.control" = { fg = "control" }
"keyword.directive" = { fg = "param" }
"keyword.storage.modifier" = { fg = "error" }

"type" = { fg = "type" }
"type.builtin" = { fg = "error" }
"type.enum.variant" = { fg = "enum" }

"constant" = { fg = "black" }
"constant.builtin" = { fg = "error" }
"constant.character" = { fg = "string" }
"constant.character.escape" = { fg = "escape" }
"string" = { fg = "string" }

"variable" = { fg = "black" }
"variable.parameter" = { fg = "param" }

"punctuation" = { fg = "param" }
"punctuation.bracket" = { fg = "black" }
"operator" = { fg = "operator" }

"function" = { fg = "function" }
"function.builtin" = { fg = "function" }
"function.macro" = { fg = "opfn" }

"tag" = "string"

"namespace" = { fg = "black" }

# Markup
"markup.heading" = { fg = "type" }
"markup.list" = { fg = "string" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "type" }
"markup.link.text" = { fg = "comment" }
"markup.link.label" = { fg = "comment" }
"markup.quote" = { fg = "enum" }
"markup.raw" = { fg = "param" }

# Errors
"warning" = "escape"
"error" = "error"
"info" = "black"
"hint" = "param"

"diagnostic.warning" = { underline = { color = "escape", style = "curl"} }
"diagnostic.error" = { underline = { color = "error", style = "curl"} }
"diagnostic.info" = { underline = { color = "black", style = "curl"} }
"diagnostic.hint" = { underline = { color = "param", style = "curl"} }

# UI common
"ui.background" = { fg = "black", bg = "white" }
"ui.text" = { fg = "black" }
"ui.text.focus" = { bg = "enabled" }
"ui.text.inactive" = { fg = "linenr" }
"ui.text.info" = { fg = "black" }
"ui.linenr" = { fg = "linenr" }
"ui.linenr.selected" = { fg = "base4" }
"ui.cursorline" = { bg = "context" }
"ui.selection" = { bg = "selection" }
"ui.cursor" = { bg = "black", fg = "white" }
"ui.cursor.match" = { bg = "match", modifiers = ["underlined"] }

# UI menus
"ui.menu" = { bg = "context", fg = "black" }
"ui.menu.selected" = { bg = "focused", fg = "black" }
"ui.popup" = { fg = "black", bg = "context" }
"ui.help" = { fg = "white", bg = "primary" }
"ui.highlight" = { bg = "line" }
"special" = "primary"

# UI editor
"ui.virtual.indent-guide" = { fg = "helpers" }
"ui.virtual.ruler" = { bg = "context" }
"ui.gutter" = { fg = "secondary" }
"ui.gutter.selected" = { fg = "black" }
"ui.window" = { fg = "primary" }

# Statusline
"ui.statusline" = { bg = "statusline", fg = "white" }
"ui.statusline.inactive" = { bg = "primary", fg = "toolbar" }
"ui.statusline.normal" = { bg = "focused", fg = "black" }
"ui.statusline.insert" = { bg = "type", fg = "white" }
"ui.statusline.select" = { bg = "comment", fg = "dark_base0" }

# Bufferline
"ui.bufferline" = { bg = "inactive", fg = "white" }
"ui.bufferline.active" = { bg = "focused", fg = "black" }
"ui.bufferline.background" = { bg = "primary" }

# Diff
"diff.plus" = "plus"
"diff.delta" = "focused"
"diff.minus" = "minus"

[palette]
white = "#FFFFFF"
black = "#000000"

accent = "#203D77"
primary = "#5D6B99"
secondary = "#C4D5FF"

inactive = "#3B4F81"
focused = "#F5CC84"
enabled = "#FFEDC8"
unfocused = "#CCD5F0"

context = "#E9EEFF"
header = "#40568D"
toolbar = "#CCD5F0"
statusline = "#40508D"

base4 = "#464646"
linenr = "#7A7A7A"
line = "#ECECEC"

# Common
comment = "#008000"
selection = "#BFCDDB"
helpers = "#2B90AF"
match = "#DBE0CC"
error = "#0000FF"
plus = "#75923C"
minus = "#FF6666"

# Syntax
type = "#2B91AF"
enum = "#2F4F4F"
function = "#74531F"
control = "#8F08C4"
param = "#808080"
macro = "#891BFF"
opfn = "#008080"
local = "#1F377F"
string = "#A31515"
operator = "#002059"
escape = "#B676FB"
