
# Syntax
"comment" = { fg = "comment" }
"attribute" = { fg = "magenta" }

"keyword" = { fg = "magenta", modifiers = ["bold"] }
"keyword.control" = { fg = "magenta", modifiers = ["bold"] }
"keyword.directive" = { fg = "blue" }
"keyword.storage.modifier" = { fg = "magenta2", modifiers = ["bold"] }
"keyword.function" = { fg = "magenta2", modifiers = ["bold"] }

"type" = { fg = "blue2" }
"type.builtin" = { fg = "oragne", modifiers = ["bold"] }

"constant" = { fg = "orange" }
"constant.builtin" = { fg = "orange", modifiers = ["bold"] }
"constant.character.escape" = { fg = "green2" }
"string" = { fg = "green" }

"variable" = { fg = "fg" }
"variable.parameter" = { fg = "blue" }

"punctuation" = { fg = "dark5" }
"punctuation.bracket" = { fg = "blue" }
"operator" = { fg = "magenta2" }

"function" = { fg = "red" }
"function.builtin" = { fg = "red", modifiers = ["bold"]}
"function.macro" = { fg = "red1" }

"namespace" = { fg = "blue0" }

# Markup
"markup.heading" = { fg = "magenta", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "magenta2", modifiers = ["bold"] }
"markup.list" = { fg = "green", modifiers = ["bold"] }
"markup.bold" = { fg = "teal", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue0" }
"markup.link.text" = { fg = "blue" }
"markup.link.label" = { fg = "blue" }
"markup.quote" = { fg = "yellow" }
"markup.raw" = { fg = "blue0" }

# Errors
"warning" = "yellow"
"error" = "red"
"info" = "blue"
"hint" = "fg"

"diagnostic.warning" = { underline = { color = "yellow", style = "curl"} }
"diagnostic.error" = { underline = { color = "red", style = "curl"} }
"diagnostic.info" = { underline = { color = "blue", style = "curl"} }
"diagnostic.hint" = { underline = { color = "fg", style = "curl"} }

# UI common
"ui.background" = { bg = "bg", fg = "fg" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "red", bg = "bg_dark", modifiers = ["bold"] }
"ui.text.inactive" = { fg = "dark3" }
"ui.text.info" = { fg = "dark5" }
"ui.linenr" = { fg = "fg_gutter" }
"ui.linenr.selected" = { fg = "fg", modifiers = ["bold"] }
"ui.cursorline" = { bg = "bg_dark" }
"ui.selection" = { bg = "bg_highlight" }
"ui.cursor" = { bg = "fg", fg = "bg" }
"ui.cursor.match" = { fg = "orange", modifiers = ["bold", "underlined"] }

# UI menus
"ui.menu" = { bg = "bg_dark", fg = "dark3" }
"ui.menu.selected" = { bg = "bg_dark", fg = "fg", modifiers = ["bold"] }
"ui.popup" = { fg = "dark3", bg = "bg_dark" }
"ui.help" = { fg = "dark3", bg = "bg_dark" }
"ui.highlight" = { bg = "bg_dark" }
"special" = "green"

# UI editor
"ui.virtual.indent-guide" = { fg = "fg_gutter" }
"ui.virtual.ruler" = { bg = "bg_dark" }
"ui.gutter" = { fg = "dark3" }
"ui.gutter.selected" = { fg = "fg" }
"ui.window" = { fg = "fg_gutter" }

# Statusline
"ui.statusline" = { bg = "bg_dark", fg = "fg" }
"ui.statusline.inactive" = { bg = "bg_dark", fg = "dark3" }
"ui.statusline.normal" = { bg = "blue", fg = "bg_dark", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "magenta2", fg = "bg_dark", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "teal", fg = "bg_dark", modifiers = ["bold"] }

# Bufferline
"ui.bufferline" = { bg = "bg_dark", fg = "fg_gutter" }
"ui.bufferline.active" = { bg = "bg", fg = "fg", modifiers = ["bold"] }

# Diff
"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"

[palette]

# Uncomment this color if u want tokyonight-storm background colors
# bg_dark = "#1f2335"
# bg = "#24283b"

bg = "#1a1b26"
bg_dark = "#16161e"
bg_highlight = "#292e42"
terminal_black = "#414868"
fg = "#c0caf5"
fg_dark = "#a9b1d6"
fg_gutter = "#3b4261"
dark3 = "#545c7e"
comment = "#565f89"
dark5 = "#737aa2"
blue0 = "#3d59a1"
blue = "#7aa2f7"
cyan = "#7dcfff"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
magenta = "#bb9af7"
magenta2 = "#ff007c"
purple = "#9d7cd8"
orange = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
green1 = "#73daca"
green2 = "#41a6b5"
teal = "#1abc9c"
red = "#f7768e"
red1 = "#db4b4b"
